FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
RUN pip install --no-cache-dir requests

# Copiar código do cliente
COPY client.py .

# Comando para iniciar o cliente
CMD ["python", "client.py"]
